const programObject = {
  UG:{
    1: "B.A.",
    2: "B.B.A.",
    3: "B.Com.",
    4: "B.F.A.",
    5: "B.Sc.",
    6: "B.Sc. Bio-Technology",
    7: "B.Sc. Computer Science",
    8: "B.Sc.Renewable Energy",
    9: "B.C.A.",
    10: "B.S.W.",
    11: "B.Tech. Chemical Engg.",
    12: "B.Tech. Civil Engg.",
    13: "B.Tech. Computer Science and Engg.",
    14: "B.Tech. Electrical Engg.",
    15: "B.Tech. Electronics Telecommunication Engg.",
    16: "B.Tech. Information Technology.",
    17: "B.Tech. Instrumentation Engg.",
    18: "B.Tech. Mechanical Engg.",
    19: "B.Tech. Production Engg.",
    20: "B.Tech. Textile Technology.",
    21: "B.A. L.L.B.",
    22: "L.L.B.",
    23: "B.Ed.",
    24: "B.P.Ed.",
    25: "B.F.A. (Sculpture & Textile Design)",
    26: "B.Pharm",
    27: "B.Sc. Hospitality Studies",
    28: "B.Sc. Bioinformatics",
    29: "B.Lib.",
    30: "B.J.",
    31: "B.Sc. Bio. Chem",
    32: "B.Sc. Food.Sc.",
    33: "B.Sc. Information Technology",
    34: "B.Voc. Retail Management",
    35: "B.Voc. Software Development",
    36: "B.Voc. Fasion Technology",
    37: "B.B.A. Agri Business Management",
    38: "B.Voc. Agriculture/Commercial Aquaculture",
    39: "B.Voc. Chemical & Petrochemicals Applied Analytical Chemistry",
    40: "B.Voc. Food Processing Technology",
    41: "B.Voc. Life Sciences/Skill Based Zoology",
    42: "B.Voc. Banking Finance Service & Insurance",
    43: "B.Voc. Retail Operation",
    44: "B.Com. Banking",
    45: "B.F.A.(Drawing & Painting)",
    46: "B.A. M.C.J.",
    47: "B.Sc. Computer Management",
    48: "B.A. Administrative Service",
    49: "B.A. Comp Animation And Web Design",
    50: "B.A. Fashion Design",
    51: "B.Voc. Appared Manufacturing And Clothing Technologh",
    52: "B.Voc. Media And Entertainment Animation VFX and Web",
    53: "B.Com. Accounting &Taxation",
    54: "B.Com. Banking and Insurance",
    55: "B.Com. Management & Entrepreneurship",
    56: "B.Voc. Cost And Management Accountancy",
    57: "B.Voc. Financial Markets",
    58: "UGC Voc. Computer Application",
    59: "UGC Voc.Foreign Trade and Practices",
    60: "B.Voc. Food Processing Preservation And Storage",
    61: "B.Voc. Web Printing Technology",
    62: "B.E. Civil Engineering.",
    63: "B.E. Electronics Engineering",
    64: "B.E. Mechanical Engg.",
    65: "B.J. & Media Science",
    66: "B.Lib. & Inf. Sci.",
    67: "B.Voc. E-Commerce And Digital Marketing",
    68: "B.Voc. Media and Entertainment",
    69: "B.Voc. Medical Latoratory Technology",
    70: "B.Sc. N.T.",
    71: "B.Sc. Software Engineering",
    72: "B.Voc. Horticulture and Post Harvest Technology",
    73: "B.Voc. Programming Skill For Software Devalopment",
    74: "B.A. Lalit kala",
    75: "B.A. (Interdisciplinary)",
    76: "Bachhelor in Hotel Management And  Catering Technology",
    77: "B.E. Comp. Sci.",
    78: "B.E. Electronics &  Communication",
    79: "B.E. Electrical",
    80: "B.E. Mechanical",
    81: "B.A. Lalit Kala (Dance, Drama, Music)",
    82: "Bacthelor of .Architecture"
  }
  ,
  Diploma: {
    1: "Diploma",
    2: "Pharm.D",
    3: "Pharm.D(P.B.)"
  },
  PG: {
    1: "M.A. Economics",
    2: "M.A. English",
    3: "M.A. Hindi",
    4: "M.A. Marathi",
    5: "M.A. Political Science",
    6: "M.A. Sociology",
    7: "M.Com.",
    8: "M.A. History",
    9: "M.Sc. Bio Technology",
    10: "M.Sc. Botany",
    11: "M.Sc. Chemistry",
    12: "M.Sc. Computer Management",
    13: "M.Sc. Computer Science",
    14: "M.Sc. Dairy Science",
    15: "M.Sc. Drug Chem.",
    16: "M.Sc. Electronics",
    17: "M.Sc. Environmental Science",
    18: "M.Sc. Information Technology",
    19: "M.Sc. Micro.Biology",
    20: "M.Sc. Multimedia",
    21: "M.Sc. Zoology",
    22: "M.Sc. Analytical Chemistry",
    23: "M.Sc. Applied Maths",
    24: "M.Sc. Herbal Medicine",
    25: "M.Sc. Mathematics",
    26: "M.Sc. Organic Chemistry",
    27: "M.Sc. Physics",
    28: "M.Sc. Statistics",
    29: "M.A. Public Administration",
    30: "M.A. Sanskrit",
    31: "M.A. Urdu",
    32: "M.S.W.",
    33: "M.Tech. Artificial Intelligence",
    34: "M.Tech. CAD/CAM.",
    35: "M.Tech. Civil Water Management Engg.",
    36: "M.Tech. Computer Network and Information Security",
    37: "M.Tech. Information Technology.",
    38: "M.Tech. Instrumentation Engg.",
    39: "M.Tech. Product Life Cycle Mgmt.",
    40: "M.Tech. StructuralEngg.",
    41: "M.Tech. Textile Technology.",
    42: "M.Tech. VLSI Embedded Systems Engg.",
    43: "L.L.M.",
    44: "M.F.A.( Painting)",
    45: "M.Pharm (Pharmacology )",
    46: "M.B.A.",
    47: "M.C.A.",
    48: "M.A. Geography",
    49: "M.Sc. Bio Informatics",
    50: "M.Sc. Software Engineering",
    51: "M.Lib. & Inf. Sci.",
    52: "M.J.",
    53: "M.sc. Biochemistry",
    54: "M.Lib.",
    55: "M.A. Music",
    56: "M.Voc. Fasion Technology Degree Programme",
    57: "M.Com.Banking & Insurance(UGC)",
    58: "L.L.M. (Business Law)",
    59: "L.L.M. (Criminal Law)",
    60: "M.A. Psychology",
    61: "Maser of Journalism",
    62: "M.Ed.",
    63: "M.A. Education",
    64: "M.A. Computer Animation VFX and Web Design",
    65: "M.A. Fashion Design",
    66: "M.Sc. Industrial Chemistry",
    67: "M.A. Philosophy",
    68: "M.Pharm (Quality Assurance)",
    69: "M.J. & M.S.",
    70: "M.Sc. Clinical Research",
    71: "M.Sc. SAN",
    72: "M.Pharm (Pharmaceutical Chemistry)",
    73: "M.Pharm (Pharmaceutics)",
    74: "M.Pharm (Pharmaceutical Quality Assurance)",
    75: "M.Pharm (Regulatory Affairs)"
  }
  ,
  "P.G.Diploma": {
    1: "P.G.D.B.M.",
    2: "P.G.D.T.L.",
    3: "P.G.Diploma In Electronics/Embeded System Design",
    4: "P.G.Diploma -Tax Pro and Practice",
    5: "P.G.Diploma",
    6: "P.G.Diploma in Taxation Law",
    7: "PGDMM",
    8: "P.G Diploma in Intellectual Property Right",
    9: "P.G.Diploma In Alternative Dispute Resolution"
  }
  ,
  "Ph.D.": {},
  Certificate: {
    1: "Certificate Course",
    2: "C.O.C.",
    3: "Certificate Course in Textile & Clothing",
    4: "Certificate Course in Travel & Tourisum",
    5: "Foundation Course"
  }
  ,
}
const Lists = {
  teamIndividual: ['Team', 'Individual'],
  SSSCategory: ["Genral", "OBC", "SC", "ST", "NT", "Others"],
  typeOfProgram: ["UG", "PG", "Ph.D", "Diploma", "PG Diploma", "Certificate"],
  StaffType: ["Teaching staff & Student", "Non-Teaching Staff"],
  cbcsEcs: ["CBCS", "ECS"],
  exams: ["NET", "SLET", "GATE", "GMAT", "GPAT", "NIPER", "CAT", "GRE", "JAM", "IELTS", "TOEFL", "Civil Services", "State Gov exams", "Any Such Other Exams"],
  Cate: ["Institution", "Teacher", "Research Scholar", "Student"],
  gender: ["Male", "Female", "Other"],
  studentAlumniSalutation: ["Mr.", "Miss.", "Mrs.", "Shri", "Shrimati"],
  casts: ["General", "OBC", "SC", "SBC", "SEBC", "ST", "VJ", "NT-B", "NT-C", "NT-D"],
  religions: ["Hindu", "Muslim", "Christian", "Sikh", "Buddh", "Jain"],
  bloodGr: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"],
  yfGgroup: ["समुह गायन - भारतीय", "समुह गायन - पाश्चात्य", "कव्वाली", "फोक ऑर्केस्ट्रा (लोक संगीत)", "लोकनृत्य / आदिवासी नृत्य", "एकांकिका", "विडंबन अभिनय", "मूक अभिनय", "वादविवाद", "कलात्मक जुळवणी (इंस्टॉलेशन)", "पोवाडा", "लावणी", "जलसा",],
  yfIndividual: ["शास्त्रीय गायन", "शास्त्रीय तालवाद्य", "शास्त्रीय सुरवाद्य", "सुगम गायन - भारतीय", "सुगम गायन - पाश्चात्य", "शास्त्रीय नृत्य", "नक्कल", "वक्तृत्व", "चित्रकला", "कोलाज", "पोस्टर पेंटिंग", "मृदमूर्तिकला", "व्यंग्यचित्रकाला", "रांगोळी", "स्थळ छायाचित्रण",],
  //patents books cahpters
  dsdIsNat: ['Inter-university', 'State', 'National', 'International'],
  patentIsNat: ["State/University", "National", "International (Abroad)", "International (within country)"],
  patentType: ["Patent", "Copyright"],
  patentStatus: ["Filed", "Published", "Awarded"],
  ConferenceOrganisedIsNational: ["State", "University", "National", "International"],
  policyDocIsNat: ["State", "National", "International"],
  policyDocOrgType: ["International Body", "Organizations like UNO / UNESCO / World Bank / IMF etc.", "Central Government / State Government"],
  bookChapConfIsNat: ["National", "International"],
  bookCapType: ["Book", "Chapter", "Editor", "Translator", "Conference",],
  bookCapTranswork: ["Research Paper / Chapter", "Book"],
  reserchProjectIsGov: ["Government", "Non-Government"],
  reserchProjectFundType: ["Major", "Minor"],
  reserchProjectStatus: ["Completed", "Ongoing"],
  eContentCreation: ["Development of Innovative Pedagogy", "Design of new curriculla & courses", "MOOCS", "E-Content"],
  eContentPlatform: ["For e-PG-Pathshala", "For CEC (Under Gaduate)", "For SWAYAM", "For MOOCs Platforms", "Any other Government Initiatives", "For Institutional LMS", "Not Available", "Other"],
  jrfsrfFellowshipType: ["JRF", "SRF", "Post Doctoral Fellows", "Research Associate"],
  invitedtalkNature: ["Invited Talk", "Resource Person", "Paper Presentation"],
  phdAwardedDegree: ["Ph.D.", "M.Phil", "PG Dissertation"],
  phdAwardedSubmit: ["Awarded", "Submitted", "Ongoing"],
  phdAwardedCategory: ["Open", "SC", "ST", "VJ / NT(A)", "VJ / NT(B)", "VJ / NT(C)", "VJ / NT(D)", "SBC", "OBC", "PH", "EWS", "Minority", "NRI", "Foreign National"],
  counselingActivities: ["Guidance for Competitive Examinations", "Guidance for Career Counselling"],
  typesOfPlacements: ["Placement", "Business Started"],
  esttNatureOfPost: ["Permanent", "Contractual", "CHB"],
  esttNatureOfAppointment: ["Permanent", "Temporary"],
  countrys: ['Afghanistan', 'Åland Islands', 'Albania', 'Algeria', 'American Samoa', 'AndorrA', 'Angola', 'Anguilla', 'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Bouvet Island', 'Brazil', 'British Indian Ocean Territory', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Christmas Island', 'Cocos (Keeling) Islands', 'Colombia', 'Comoros', 'Congo', 'Congo, The Democratic Republic of the', 'Cook Islands', 'Costa Rica', 'Cote D\'Ivoire', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Falkland Islands (Malvinas)', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia', 'French Southern Territories', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heard Island and Mcdonald Islands', 'Holy See (Vatican City State)', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Republic Of', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Korea, Democratic People\'S Republic of', 'Korea, Republic of', 'Kuwait', 'Kyrgyzstan', 'Lao People\'S Democratic Republic', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libyan Arab Jamahiriya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao', 'Macedonia, The Former Yugoslav Republic of', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico', 'Micronesia, Federated States of', 'Moldova, Republic of', 'Monaco', 'Mongolia', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'Netherlands Antilles', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk Island', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestinian Territory, Occupied', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Reunion', 'Romania', 'Russian Federation', 'RWANDA', 'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia and Montenegro', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Georgia and the South Sandwich Islands', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Svalbard and Jan Mayen', 'Swaziland', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Taiwan, Province of China', 'Tajikistan', 'Tanzania, United Republic of', 'Thailand', 'Timor-Leste', 'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'United States Minor Outlying Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Viet Nam', 'Virgin Islands, British', 'Virgin Islands, U.S.', 'Wallis and Futuna', 'Western Sahara', 'Yemen', 'Zambia', 'Zimbabwe',],
  statesInIndia: {
    "Andhra Pradesh": [
      "Anantapur",
      "Chittoor",
      "East Godavari",
      "Guntur",
      "Krishna",
      "Kurnool",
      "Nellore",
      "Prakasam",
      "Srikakulam",
      "Visakhapatnam",
      "Vizianagaram",
      "West Godavari",
      "YSR Kadapa",
    ],
    "Arunachal Pradesh": [
      "Tawang",
      "West Kameng",
      "East Kameng",
      "Papum Pare",
      "Kurung Kumey",
      "Kra Daadi",
      "Lower Subansiri",
      "Upper Subansiri",
      "West Siang",
      "East Siang",
      "Siang",
      "Upper Siang",
      "Lower Siang",
      "Lower Dibang Valley",
      "Dibang Valley",
      "Anjaw",
      "Lohit",
      "Namsai",
      "Changlang",
      "Tirap",
      "Longding",
    ],
    "Assam": [
      "Baksa",
      "Barpeta",
      "Biswanath",
      "Bongaigaon",
      "Cachar",
      "Charaideo",
      "Chirang",
      "Darrang",
      "Dhemaji",
      "Dhubri",
      "Dibrugarh",
      "Goalpara",
      "Golaghat",
      "Hailakandi",
      "Hojai",
      "Jorhat",
      "Kamrup Metropolitan",
      "Kamrup",
      "Karbi Anglong",
      "Karimganj",
      "Kokrajhar",
      "Lakhimpur",
      "Majuli",
      "Morigaon",
      "Nagaon",
      "Nalbari",
      "Dima Hasao",
      "Sivasagar",
      "Sonitpur",
      "South Salmara-Mankachar",
      "Tinsukia",
      "Udalguri",
      "West Karbi Anglong",
    ],
    "Bihar": [
      "Araria",
      "Arwal",
      "Aurangabad",
      "Banka",
      "Begusarai",
      "Bhagalpur",
      "Bhojpur",
      "Buxar",
      "Darbhanga",
      "East Champaran (Motihari)",
      "Gaya",
      "Gopalganj",
      "Jamui",
      "Jehanabad",
      "Kaimur (Bhabua)",
      "Katihar",
      "Khagaria",
      "Kishanganj",
      "Lakhisarai",
      "Madhepura",
      "Madhubani",
      "Munger (Monghyr)",
      "Muzaffarpur",
      "Nalanda",
      "Nawada",
      "Patna",
      "Purnia (Purnea)",
      "Rohtas",
      "Saharsa",
      "Samastipur",
      "Saran",
      "Sheikhpura",
      "Sheohar",
      "Sitamarhi",
      "Siwan",
      "Supaul",
      "Vaishali",
      "West Champaran",
    ],
    "Chandigarh (UT)": ["Chandigarh"],
    "Chhattisgarh": [
      "Balod",
      "Baloda Bazar",
      "Balrampur",
      "Bastar",
      "Bemetara",
      "Bijapur",
      "Bilaspur",
      "Dantewada (South Bastar)",
      "Dhamtari",
      "Durg",
      "Gariyaband",
      "Janjgir-Champa",
      "Jashpur",
      "Kabirdham (Kawardha)",
      "Kanker (North Bastar)",
      "Kondagaon",
      "Korba",
      "Korea (Koriya)",
      "Mahasamund",
      "Mungeli",
      "Narayanpur",
      "Raigarh",
      "Raipur",
      "Rajnandgaon",
      "Sukma",
      "Surajpur  ",
      "Surguja",
    ],
    "Dadra and Nagar Haveli (UT)": ["Dadra & Nagar Haveli"],
    "Daman and Diu (UT)": ["Daman", "Diu"],
    "Delhi (NCT)": [
      "Central Delhi",
      "East Delhi",
      "New Delhi",
      "North Delhi",
      "North East  Delhi",
      "North West  Delhi",
      "Shahdara",
      "South Delhi",
      "South East Delhi",
      "South West  Delhi",
      "West Delhi",
    ],
    "Goa": ["North Goa", "South Goa"],
    "Gujarat": [
      "Ahmedabad",
      "Amreli",
      "Anand",
      "Aravalli",
      "Banaskantha (Palanpur)",
      "Bharuch",
      "Bhavnagar",
      "Botad",
      "Chhota Udepur",
      "Dahod",
      "Dangs (Ahwa)",
      "Devbhoomi Dwarka",
      "Gandhinagar",
      "Gir Somnath",
      "Jamnagar",
      "Junagadh",
      "Kachchh",
      "Kheda (Nadiad)",
      "Mahisagar",
      "Mehsana",
      "Morbi",
      "Narmada (Rajpipla)",
      "Navsari",
      "Panchmahal (Godhra)",
      "Patan",
      "Porbandar",
      "Rajkot",
      "Sabarkantha (Himmatnagar)",
      "Surat",
      "Surendranagar",
      "Tapi (Vyara)",
      "Vadodara",
      "Valsad",
    ],
    "Haryana": [
      "Ambala",
      "Bhiwani",
      "Charkhi Dadri",
      "Faridabad",
      "Fatehabad",
      "Gurgaon",
      "Hisar",
      "Jhajjar",
      "Jind",
      "Kaithal",
      "Karnal",
      "Kurukshetra",
      "Mahendragarh",
      "Mewat",
      "Palwal",
      "Panchkula",
      "Panipat",
      "Rewari",
      "Rohtak",
      "Sirsa",
      "Sonipat",
      "Yamunanagar",
    ],
    "Himachal Pradesh": [
      "Bilaspur",
      "Chamba",
      "Hamirpur",
      "Kangra",
      "Kinnaur",
      "Kullu",
      "Lahaul &amp; Spiti",
      "Mandi",
      "Shimla",
      "Sirmaur (Sirmour)",
      "Solan",
      "Una",
    ],
    "Jammu and Kashmir": [
      "Anantnag",
      "Bandipore",
      "Baramulla",
      "Budgam",
      "Doda",
      "Ganderbal",
      "Jammu",
      "Kargil",
      "Kathua",
      "Kishtwar",
      "Kulgam",
      "Kupwara",
      "Leh",
      "Poonch",
      "Pulwama",
      "Rajouri",
      "Ramban",
      "Reasi",
      "Samba",
      "Shopian",
      "Srinagar",
      "Udhampur",
    ],
    "Jharkhand": [
      "Bokaro",
      "Chatra",
      "Deoghar",
      "Dhanbad",
      "Dumka",
      "East Singhbhum",
      "Garhwa",
      "Giridih",
      "Godda",
      "Gumla",
      "Hazaribag",
      "Jamtara",
      "Khunti",
      "Koderma",
      "Latehar",
      "Lohardaga",
      "Pakur",
      "Palamu",
      "Ramgarh",
      "Ranchi",
      "Sahibganj",
      "Seraikela-Kharsawan",
      "Simdega",
      "West Singhbhum",
    ],
    "Karnataka": [
      "Bagalkot",
      "Ballari (Bellary)",
      "Belagavi (Belgaum)",
      "Bengaluru (Bangalore) Rural",
      "Bengaluru (Bangalore) Urban",
      "Bidar",
      "Chamarajanagar",
      "Chikballapur",
      "Chikkamagaluru (Chikmagalur)",
      "Chitradurga",
      "Dakshina Kannada",
      "Davangere",
      "Dharwad",
      "Gadag",
      "Hassan",
      "Haveri",
      "Kalaburagi (Gulbarga)",
      "Kodagu",
      "Kolar",
      "Koppal",
      "Mandya",
      "Mysuru (Mysore)",
      "Raichur",
      "Ramanagara",
      "Shivamogga (Shimoga)",
      "Tumakuru (Tumkur)",
      "Udupi",
      "Uttara Kannada (Karwar)",
      "Vijayapura (Bijapur)",
      "Yadgir",
    ],
    "Kerala": [
      "Alappuzha",
      "Ernakulam",
      "Idukki",
      "Kannur",
      "Kasaragod",
      "Kollam",
      "Kottayam",
      "Kozhikode",
      "Malappuram",
      "Palakkad",
      "Pathanamthitta",
      "Thiruvananthapuram",
      "Thrissur",
      "Wayanad",
    ],
    "Lakshadweep (UT)": [
      "Agatti",
      "Amini",
      "Androth",
      "Bithra",
      "Chethlath",
      "Kavaratti",
      "Kadmath",
      "Kalpeni",
      "Kilthan",
      "Minicoy",
    ],
    "Madhya Pradesh": [
      "Agar Malwa",
      "Alirajpur",
      "Anuppur",
      "Ashoknagar",
      "Balaghat",
      "Barwani",
      "Betul",
      "Bhind",
      "Bhopal",
      "Burhanpur",
      "Chhatarpur",
      "Chhindwara",
      "Damoh",
      "Datia",
      "Dewas",
      "Dhar",
      "Dindori",
      "Guna",
      "Gwalior",
      "Harda",
      "Hoshangabad",
      "Indore",
      "Jabalpur",
      "Jhabua",
      "Katni",
      "Khandwa",
      "Khargone",
      "Mandla",
      "Mandsaur",
      "Morena",
      "Narsinghpur",
      "Neemuch",
      "Panna",
      "Raisen",
      "Rajgarh",
      "Ratlam",
      "Rewa",
      "Sagar",
      "Satna",
      "Sehore",
      "Seoni",
      "Shahdol",
      "Shajapur",
      "Sheopur",
      "Shivpuri",
      "Sidhi",
      "Singrauli",
      "Tikamgarh",
      "Ujjain",
      "Umaria",
      "Vidisha",
    ],
    "Maharashtra": [
      "Ahmednagar",
      "Akola",
      "Amravati",
      "Aurangabad",
      "Beed",
      "Bhandara",
      "Buldhana",
      "Chandrapur",
      "Dhule",
      "Gadchiroli",
      "Gondia",
      "Hingoli",
      "Jalgaon",
      "Jalna",
      "Kolhapur",
      "Latur",
      "Mumbai City",
      "Mumbai Suburban",
      "Nagpur",
      "Nanded",
      "Nandurbar",
      "Nashik",
      "Osmanabad",
      "Palghar",
      "Parbhani",
      "Pune",
      "Raigad",
      "Ratnagiri",
      "Sangli",
      "Satara",
      "Sindhudurg",
      "Solapur",
      "Thane",
      "Wardha",
      "Washim",
      "Yavatmal",
    ],
    "Manipur": [
      "Bishnupur",
      "Chandel",
      "Churachandpur",
      "Imphal East",
      "Imphal West",
      "Jiribam",
      "Kakching",
      "Kamjong",
      "Kangpokpi",
      "Noney",
      "Pherzawl",
      "Senapati",
      "Tamenglong",
      "Tengnoupal",
      "Thoubal",
      "Ukhrul",
    ],
    "Meghalaya": [
      "East Garo Hills",
      "East Jaintia Hills",
      "East Khasi Hills",
      "North Garo Hills",
      "Ri Bhoi",
      "South Garo Hills",
      "South West Garo Hills ",
      "South West Khasi Hills",
      "West Garo Hills",
      "West Jaintia Hills",
      "West Khasi Hills",
    ],
    "Mizoram": [
      "Aizawl",
      "Champhai",
      "Kolasib",
      "Lawngtlai",
      "Lunglei",
      "Mamit",
      "Saiha",
      "Serchhip",
    ],
    "Nagaland": [
      "Dimapur",
      "Kiphire",
      "Kohima",
      "Longleng",
      "Mokokchung",
      "Mon",
      "Peren",
      "Phek",
      "Tuensang",
      "Wokha",
      "Zunheboto",
    ],
    "Odisha": [
      "Angul",
      "Balangir",
      "Balasore",
      "Bargarh",
      "Bhadrak",
      "Boudh",
      "Cuttack",
      "Deogarh",
      "Dhenkanal",
      "Gajapati",
      "Ganjam",
      "Jagatsinghapur",
      "Jajpur",
      "Jharsuguda",
      "Kalahandi",
      "Kandhamal",
      "Kendrapara",
      "Kendujhar (Keonjhar)",
      "Khordha",
      "Koraput",
      "Malkangiri",
      "Mayurbhanj",
      "Nabarangpur",
      "Nayagarh",
      "Nuapada",
      "Puri",
      "Rayagada",
      "Sambalpur",
      "Sonepur",
      "Sundargarh",
    ],
    "Puducherry (UT)": ["Karaikal", "Mahe", "Pondicherry", "Yanam"],
    "Punjab": [
      "Amritsar",
      "Barnala",
      "Bathinda",
      "Faridkot",
      "Fatehgarh Sahib",
      "Fazilka",
      "Ferozepur",
      "Gurdaspur",
      "Hoshiarpur",
      "Jalandhar",
      "Kapurthala",
      "Ludhiana",
      "Mansa",
      "Moga",
      "Muktsar",
      "Nawanshahr (Shahid Bhagat Singh Nagar)",
      "Pathankot",
      "Patiala",
      "Rupnagar",
      "Sahibzada Ajit Singh Nagar (Mohali)",
      "Sangrur",
      "Tarn Taran",
    ],
    "Rajasthan": [
      "Ajmer",
      "Alwar",
      "Banswara",
      "Baran",
      "Barmer",
      "Bharatpur",
      "Bhilwara",
      "Bikaner",
      "Bundi",
      "Chittorgarh",
      "Churu",
      "Dausa",
      "Dholpur",
      "Dungarpur",
      "Hanumangarh",
      "Jaipur",
      "Jaisalmer",
      "Jalore",
      "Jhalawar",
      "Jhunjhunu",
      "Jodhpur",
      "Karauli",
      "Kota",
      "Nagaur",
      "Pali",
      "Pratapgarh",
      "Rajsamand",
      "Sawai Madhopur",
      "Sikar",
      "Sirohi",
      "Sri Ganganagar",
      "Tonk",
      "Udaipur",
    ],
    "Sikkim": ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
    "Tamil Nadu": [
      "Ariyalur",
      "Chennai",
      "Coimbatore",
      "Cuddalore",
      "Dharmapuri",
      "Dindigul",
      "Erode",
      "Kanchipuram",
      "Kanyakumari",
      "Karur",
      "Krishnagiri",
      "Madurai",
      "Nagapattinam",
      "Namakkal",
      "Nilgiris",
      "Perambalur",
      "Pudukkottai",
      "Ramanathapuram",
      "Salem",
      "Sivaganga",
      "Thanjavur",
      "Theni",
      "Thoothukudi (Tuticorin)",
      "Tiruchirappalli",
      "Tirunelveli",
      "Tiruppur",
      "Tiruvallur",
      "Tiruvannamalai",
      "Tiruvarur",
      "Vellore",
      "Viluppuram",
      "Virudhunagar",
    ],
    "Telangana": [
      "Adilabad",
      "Bhadradri Kothagudem",
      "Hyderabad",
      "Jagtial",
      "Jangaon",
      "Jayashankar Bhoopalpally",
      "Jogulamba Gadwal",
      "Kamareddy",
      "Karimnagar",
      "Khammam",
      "Komaram Bheem Asifabad",
      "Mahabubabad",
      "Mahabubnagar",
      "Mancherial",
      "Medak",
      "Medchal",
      "Nagarkurnool",
      "Nalgonda",
      "Nirmal",
      "Nizamabad",
      "Peddapalli",
      "Rajanna Sircilla",
      "Rangareddy",
      "Sangareddy",
      "Siddipet",
      "Suryapet",
      "Vikarabad",
      "Wanaparthy",
      "Warangal (Rural)",
      "Warangal (Urban)",
      "Yadadri Bhuvanagiri",
    ],
    "Tripura": [
      "Dhalai",
      "Gomati",
      "Khowai",
      "North Tripura",
      "Sepahijala",
      "South Tripura",
      "Unakoti",
      "West Tripura",
    ],
    "Uttarakhand": [
      "Almora",
      "Bageshwar",
      "Chamoli",
      "Champawat",
      "Dehradun",
      "Haridwar",
      "Nainital",
      "Pauri Garhwal",
      "Pithoragarh",
      "Rudraprayag",
      "Tehri Garhwal",
      "Udham Singh Nagar",
      "Uttarkashi",
    ],
    "Uttar Pradesh": [
      "Agra",
      "Aligarh",
      "Allahabad",
      "Ambedkar Nagar",
      "Amethi (Chatrapati Sahuji Mahraj Nagar)",
      "Amroha (J.P. Nagar)",
      "Auraiya",
      "Azamgarh",
      "Baghpat",
      "Bahraich",
      "Ballia",
      "Balrampur",
      "Banda",
      "Barabanki",
      "Bareilly",
      "Basti",
      "Bhadohi",
      "Bijnor",
      "Budaun",
      "Bulandshahr",
      "Chandauli",
      "Chitrakoot",
      "Deoria",
      "Etah",
      "Etawah",
      "Faizabad",
      "Farrukhabad",
      "Fatehpur",
      "Firozabad",
      "Gautam Buddha Nagar",
      "Ghaziabad",
      "Ghazipur",
      "Gonda",
      "Gorakhpur",
      "Hamirpur",
      "Hapur (Panchsheel Nagar)",
      "Hardoi",
      "Hathras",
      "Jalaun",
      "Jaunpur",
      "Jhansi",
      "Kannauj",
      "Kanpur Dehat",
      "Kanpur Nagar",
      "Kanshiram Nagar (Kasganj)",
      "Kaushambi",
      "Kushinagar (Padrauna)",
      "Lakhimpur - Kheri",
      "Lalitpur",
      "Lucknow",
      "Maharajganj",
      "Mahoba",
      "Mainpuri",
      "Mathura",
      "Mau",
      "Meerut",
      "Mirzapur",
      "Moradabad",
      "Muzaffarnagar",
      "Pilibhit",
      "Pratapgarh",
      "RaeBareli",
      "Rampur",
      "Saharanpur",
      "Sambhal (Bhim Nagar)",
      "Sant Kabir Nagar",
      "Shahjahanpur",
      "Shamali (Prabuddh Nagar)",
      "Shravasti",
      "Siddharth Nagar",
      "Sitapur",
      "Sonbhadra",
      "Sultanpur",
      "Unnao",
      "Varanasi",
    ],
    "West Bengal": [
      "Alipurduar",
      "Bankura",
      "Birbhum",
      "Burdwan (Bardhaman)",
      "Cooch Behar",
      "Dakshin Dinajpur (South Dinajpur)",
      "Darjeeling",
      "Hooghly",
      "Howrah",
      "Jalpaiguri",
      "Kalimpong",
      "Kolkata",
      "Malda",
      "Murshidabad",
      "Nadia",
      "North 24 Parganas",
      "Paschim Medinipur (West Medinipur)",
      "Purba Medinipur (East Medinipur)",
      "Purulia",
      "South 24 Parganas",
      "Uttar Dinajpur (North Dinajpur)",
    ],
  },
};
export default Lists;

export {programObject};