const staticData = {
    Equipment: {
      Equipment1: {
        1: {name: `Thermo balance (TGA/DTA)`, location: `School of Chemical science`, quantity: 1, costPerUnit: "0.3 Cr", totalCost: "0.30 Cr"},
        2: {name: `FT-IR Portable`, location: `School of Chemical science. CIC, School of Life Science & School of Pharmacy`, quantity: 4, costPerUnit: "0.12 Cr", totalCost: "0.48 Cr"},
        3: {name: `UV VIS Spectrophotometer Double Beam`, location: `School of Life Science, School of Chemical science & School of Earth Science`, quantity: 4 , costPerUnit: "0.09 Cr ", totalCost: "0.36 Cr "},
        4: {name: `Cooling Centrifuge machine`, location: `School of Life Science, School of Chemical science & School of Pharmacy`, quantity: 5, costPerUnit: "0.06 Cr", totalCost: "0.30 Cr"},
        5: {name: `Binocular compound microscope`, location: `School of Life Science, School of Pharmacy & School of Earth Science`, quantity: 100, costPerUnit: "0.004 Cr", totalCost: "0.40 Cr"},
        6: {name: `Cooling Shaking Incubator`, location: `School of Life Science & School of Pharmacy `, quantity: 6, costPerUnit: "0.03 Cr", totalCost: "0.18 Cr"},
        7: {name: `Sensitive single pan balances`, location: `School of Life Science, School of Chemical science, School of Physical Science, School of Earth Science & School of Pharmacy`, quantity: 10, costPerUnit: "0.015 Cr", totalCost: "0.15 Cr"},
        8: {name: `Rotary Evaporator with chillers and vacuum pump`, location: `School of Life Science, School of Chemical science & School of Pharmacy`, quantity: 5, costPerUnit: "0.06 Cr", totalCost: "0.30 Cr"},
        9: {name: `Karl Fisher titrator`, location: `School of Chemical science`, quantity: 1, costPerUnit: "0.07 Cr", totalCost: "0.07 Cr"},
        10: {name: `GPS (Garmin make)`, location: `School of Earth Science`, quantity: 4, costPerUnit: "0.005 Cr", totalCost: "0.02 Cr"},
        11: {name: `Tablet analyser`, location: `School of Pharmacy`, quantity: 1, costPerUnit: "0.05 Cr", totalCost: "0.05 Cr"},
        12: {name: `Haematology analyser`, location: `School of Pharmacy`, quantity: 1, costPerUnit: "0.020 Cr", totalCost: "0.02 Cr"},
      }
    },
    Soft: {
      Soft1: {
        1:{ activity: "LIGO-India" },
        2:{ activity: "Diversity of Medicinal Plants, Utilization and Conservation" },
        3:{ activity: "Seminar on Data Analytics and Its Application" },
        4:{ activity: "Tribal development" },
        5:{ activity: "Machine Learning and Data Science" },
        6:{ activity: "Computer-Aided Drug Designing" },
        7:{ activity: "Climate Change" },
        8:{ activity: "Astronomy and Astrophysics" },
        9:{ activity: "Innovations and Applications in Life Sciences" },
        10:{ activity: "Research Methodology on Tribal Studies" },
        11:{ activity: "Dynamics in Financial Sector: Opportunities and Challenges" },
      },
      // activity: <></>, purpose: <ul style={{listStyleType: "disc"}}><li>To enhance association with academic and the research institutes, industries, society, for academic research enrichment</li><li>To enhance the extension activities</li><li>To enhance alumni association and participation in various academic research and extension activities</li></ul>, details: "This activity will be continuously organised by various school and administration", unit: 18, costPerUnit: "0.05 Cr", totalCost: "0.90 Cr", noOfBeneficiaries: 10000},

      Soft2: {
        1:{ activity: "LIGO-India mega science" },
        2:{ activity: "E-Content Development for students" },
        3:{ activity: "Research methodology for final year students" },
        4:{ activity: "Data analysis using Excel for final year students" },
        5:{ activity: "Awareness of Free and open-source software" },
        6:{ activity: "ICT tools for Teaching, Learning and Evaluation" },
        7:{ activity: "Training program for teachers" },
        8:{ activity: "Internet of Things (IoT)" },
        9:{ activity: "Renewable Energy related soft skills for students" },
        10:{ activity: "Geospatial Technologies" },
        11:{ activity: "Application of SPSS and Data Analysis" },
        12:{ activity: "Feminist Research Methodologies" },
      },
      // activity: <></>, purpose: "To enhance skills in one or more area expertise among the students. Increase motivations to identify the challenges to connect objectives of selected goal which are realistic and attend able Research and Development, Skill Development", details: "Each department once per six months training programme will organised for final year students as well as supporting staff", unit: 75, costPerUnit: "0.01 Cr", totalCost: "0.75 Cr", noOfBeneficiaries: 10000},

      Soft3: {
        1:{ activity: "Training and Development Activity" },
        2:{ activity: "IPR activities" },
        3:{ activity: "Communication Skills" },
        4:{ activity: "Seminar & Workshop & HR Meet" },
        5:{ activity: "Roll play on Recent Development" },
        6:{ activity: "Group Discussion and personal Interview" },
        7:{ activity: "Logical Reasoning workshop" },
        8:{ activity: "Resume writing and Interview Techniques" },
        9:{ activity: "Entrepreneurship Development Activity" },
        10:{ activity: "Business plan activities" },
        11:{ activity: "Business plan competition" },
        12:{ activity: "Creative business activity" },
        13:{ activity: "Financial planning for business" },
        14:{ activity: "Innovative business idea" },
        15:{ activity: "Launching new business" },
        16:{ activity: "Business English" },
        17:{ activity: "Personality Development and Corporate Skills" },
        18:{ activity: "Critical Thinking & Problems Solving" },
        19:{ activity: "Digital Education" },
        20:{ activity: "Team Building & Employability Skills" },
      },
      // activity: <></>, purpose: "To enhance employability among to graduate of university and colleges as well as to create abilities to start their business and entrepreneurships. ", details: "Every year for last semester student's placement and entrepreneurship activity. ", unit: 50, costPerUnit: "0.01 Cr", totalCost: "0.50 Cr", noOfBeneficiaries: 20000},
      Soft4: {
        1:{ activity: "NEP 2020 Workshops for teacher" },
        2:{ activity: "Capacity building" },
        3:{ activity: "Curriculum framing" },
        4:{ activity: "Research Skill Development" },
        5:{ activity: "Understanding educational standard and framework" },
        6:{ activity: "Teaching Skill Development" },
        7:{ activity: "Research Methodology" },
        8:{ activity: "In corporatizing emerging technology in education" },
        9:{ activity: "Project Based Learning & Assessment " },
        10:{ activity: "Research Paper Publication & how to write research paper " },
        11:{ activity: "Collaboration and Knowledge exchange amount educator to industries " },
        12:{ activity: "Innovative & Technological Teaching Skill" },
      },
        // activity: <></>, purpose: "For Upgradation of current knowledge in pedagogical training for effective teaching, class management and to develop of art of expressing and overall development in profession", details: "Every year for university campuses and affiliated college teachers.", unit: 12, costPerUnit: "0.02 Cr", totalCost: "0.24 Cr", noOfBeneficiaries: 1000},
      Soft5: {
        1:{ activity: "Tutoring and Coaching" },
        2:{ activity: "Assisting in the personal development plan." },
        3:{ activity: "To develop interest among students for solving the problem of community" },
        4:{ activity: "Motivate to develop his/her career to serve in administrative services to implement government policy to common individuals" },
      },
        // activity: <></>, purpose: <><ul><li>To help the students to learn faster for personal and career goal enhance to self-confidence and improve interpersonal skill</li><li>Improve the reading, and creative writing abilities.</li><li>Improve problem-solving and critical thinking abilities</li><li>Improve self-assessment of academic abilities and areas in which more education and training is required.</li></ul>, details: <ul><li>Goal oriented discussion</li><li>seminars of seniors</li><li>self-improvement, regarding accountability</li></ul>(13 Schools on main campus, 3 Schools on Latur sub-campus, 1 sub campus Parbhani and 1 Kinwat) total 18 School Campuses will be run mentorship activities for their students.</>, unit: 2, costPerUnit: "0.03 Cr", totalCost: "0.06 Cr", noOfBeneficiaries: 4000},
      Soft6: {
        1:{ activity: "Animation and multimedia" },
        2:{ activity: "Web designing" },
        3:{ activity: "Graphics Designing" },
        4:{ activity: "Photography / Videography" },
        5:{ activity: "Interior designing" },
        6:{ activity: "Fashion designing" },
        7:{ activity: "Pharmacy" },
        8:{ activity: "Digital Marketing" },
        9:{ activity: "Industrial training" },
        10:{ activity: "Human resource management" },
        11:{ activity: "Agriculture" },        
      },
        // activity: <></>, purpose: "The students from university campus and affiliated college should gain knowledge of skill as per his/her interest in addition to curriculum knowledge. The acquired skill through vocational training programme will develop employability in industries/business at local and national level. The university campuses and affiliated colleges have already started vocational courses the university will arrange training for vocational courses to gain practical experience in their chosen carrier as well as their skill and capabilities", details: "Workshops and advanced training programmes will be organized for vocational student's course wise. (Already running vocational courses in campus school will also strengthening by providing some expertise under this scheme)", unit: 60, costPerUnit: "0.0025 Cr", totalCost: "0.15 Cr", noOfBeneficiaries: 3000},
      Soft7: {
        1: {activity: "Structure, curriculum and pedagogy"},
        2: {activity: "teaching-learning strategies"},
        3: {activity: "learning resources and technology-enabled learning"},
        4: {activity: "vocational education and skilling and employability"},
        5: {activity: "21st century learning and social and life skills"},
        6: {activity: "optimal learning environment and learner support"},
        7: {activity: "formative and summative assessment"},
        8: {activity: "internationalization, research and scholarship"},
        9: {activity: "Governance and leadership, and regulation and accreditation."},
      },
        // activity: <></>, purpose: "To enhance holistic development, flexible learning, inclusive education, skill development among the students, professional development and integration of technology", details: "This activity will be carried out through seminar, workshop, discussion of industries professionals and scientist from research organisation at national level will be arranged frequently for the student's parents andsociety to understand importance of new education policy", unit: 96, costPerUnit: "0.00125 Cr", totalCost: "0.12 Cr", noOfBeneficiaries: 300000},
      Soft8: {
        1: { activity: "Foundations of Innovative Leadership "},
        2: { activity: "Implementing Innovative Practices "},
        3: { activity: "Design Thinking for Education (Weeks 4-6)"},
        4: { activity: "Leading Change in Educational Settings (Weeks 7-9) "},
        5: { activity: "Cultivating a Culture of Innovation (Weeks 10-12)"},
      },
        // activity: <></>, purpose: "Up skilling", details: "For Students Personality Development for 100 Students batch", unit: 7, costPerUnit: "0.01 Cr", totalCost: "0.07 Cr", noOfBeneficiaries: 600},
      Soft9: {
        1: { activity: "Computer aided drug discovery software" },
        2: { activity: "cyber security social Media Personality development" },
      },
        // activity: <></>, purpose: "In depth knowledge of applicability of ICT in societal use among the graduates and post graduates", details: "programme will be organised for the batch of 200 students both online and offline mode", unit: 12, costPerUnit: "0.005 Cr", totalCost: "0.06 Cr", noOfBeneficiaries: 1200},
      Soft10: {
        1: { activity: "GC-MS, UPLC and HRMS" },
        2: { activity: "handling of experiment Animals" },
        3: { activity: "Preparative HPLC and HPLC" },
        4: { activity: "Computer Aided Drug Discovery software" },
        5: { activity: "Cyber-security" },
        6: { activity: "AI, ML, DL" },
        7: { activity: "Scientific computing" },
      },
        // activity: <></>, purpose: "To improve data integrity and to reduce human error among the latest computer knowledge aspirants", details: "Program on thrust area of one week duration", unit: 6, costPerUnit: "0.01 Cr", totalCost: "0.06 Cr", noOfBeneficiaries: 1200},
    },
}

const SoftSubTitle = {
  Soft1: "Conferences, Workshop, Seminars",
  Soft2: "Training Programme",
  Soft3: "Training and Entrepreneurship activity",
  Soft4: "Training programme for teachers",
  Soft5: "Mentorship Mentoring activity",
  Soft6: "Vocational courses Training programme Diploma courses in",
  Soft7: "Online Training programme for students Training programmes on important component of NEP 2020 will be organised.",
  Soft8: "Certificate course in Entrepreneurship, Leadership and Change Management Development.",
  Soft9: "Conduction of awareness programs in computational domain like cyber security, social media, application of specific software, etc.",
  Soft10: "Conduction of hands-on training programs on latest trends in computer field like scientific computing, AI, ML, DL and cyber security - Hands on training on",
}

const statusColor = {
    "Not yet Started": "#E84C3D", 
    Ongoing: "#F39C11", 
    Completed: "#18BB9C", 
    "Tender Invited": "#F39C11", 
    "Not yet purchased": "#E84C3D", 
    Purchased: "#3598DB", 
    "Installation completed": "#18BB9C"
  }

export { staticData, SoftSubTitle, statusColor } 